[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".


# Primary accent color for interactive elements.
primaryColor = "#F19A3E"

# Background color for the main content area.
backgroundColor = "#403233"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor ="#F19A3E"

# Color used for almost all text.
textColor = "#ABEDC6"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "monospace"